version: "3.9"
services:

  bot:
    build:
      context: .
      network: host
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
